# Generated by Django 4.1.4 on 2022-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_categorias_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(max_length=1000),
        ),
    ]
