# Generated by Django 4.1.4 on 2022-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_comentario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaparte',
            name='mensaje',
            field=models.CharField(max_length=2000),
        ),
    ]
