# Generated by Django 4.1.4 on 2022-12-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticiaparte_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaparte',
            name='mensaje',
            field=models.TextField(max_length=10000),
        ),
    ]
